# Generated by Django 6.0.7 on 2026-07-29 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Both')], default='customer', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_type', models.CharField(default='খুচরা গ্রাহক', max_length=100)),
                ('supply_type', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('alt_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(default='বাংলাদেশ', max_length=100)),
                ('division', models.CharField(default='ঢাকা', max_length=100)),
                ('district', models.CharField(default='ঢাকা', max_length=100)),
                ('thana', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('id_type', models.CharField(default='NID', max_length=50)),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_days', models.IntegerField(default=30)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Dokan ERP', max_length=255)),
                ('phone', models.CharField(default='01700000000', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@dokan.com', max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='Dhaka, Bangladesh')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='৳', max_length=20)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('receipt_footer', models.TextField(blank=True, default='ধন্যবাদ, আবার আসবেন!')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='সাধারণ খরচ', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(default='ক্যাশ', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bank')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('unit', models.CharField(default='পিস', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('payment_in', 'Payment In'), ('payment_out', 'Payment Out')], db_index=True, default='sale', max_length=30)),
                ('status', models.CharField(default='completed', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking'), ('split', 'Split')], default='cash', max_length=30)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_due_date', models.DateField(blank=True, null=True)),
                ('cheque_status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bank')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.party')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit', models.CharField(default='পিস', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.transaction')),
            ],
        ),
    ]
