# Generated by Django 6.0.7 on 2026-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='party',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='party',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
