# Generated by Django 6.0.7 on 2026-07-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_party_total_due_party_total_purchases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
