# Generated by Django 5.2.16 on 2026-08-05 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hawlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default='সাধারণ হাওলাত', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hawlats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='party',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
