# Generated by Django 5.2.16 on 2026-08-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hawlat_alter_expense_date_alter_party_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawlat',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hawlat',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
