# Generated by Django 5.2.16 on 2026-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hawlat_is_settled_hawlat_settled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_price_review',
            field=models.BooleanField(default=False),
        ),
    ]
