# Generated by Django 5.2.16 on 2026-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_needs_price_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
