# Generated by Django 5.2.16 on 2026-08-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transactionitem_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='cost_price',
        ),
    ]
