# Generated by Django 5.2.16 on 2026-08-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_transactionitem_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('engineer', 'Engineer'), ('both', 'Both')], default='customer', max_length=20),
        ),
    ]
