# Generated by Django 5.2.16 on 2026-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('developer', 'ডেভেলপার (Developer - Full Access & Invoice Edit/Delete)'), ('admin', 'অ্যাডমিন (Admin - All Operations Except Invoice Edit/Delete)'), ('staff', 'স্টাফ (Staff - View Only)')], default='staff', max_length=20),
        ),
    ]
