# Generated by Django 5.2.16 on 2026-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_party_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
