# Generated by Django 5.2.16 on 2026-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_opening_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='district',
            field=models.CharField(default='গোপালগঞ্জ', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('payment_in', 'Payment In'), ('payment_out', 'Payment Out'), ('loan_in', 'Loan In / লোন গ্রহণ')], db_index=True, default='sale', max_length=30),
        ),
    ]
