# Generated by Django 5.2.16 on 2026-09-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='commission_pin',
            field=models.CharField(blank=True, default='1234', max_length=100, null=True),
        ),
    ]
