# Generated by Django 5.2.16 on 2026-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shopsettings_commission_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
